packaging_format = 2

id = "audiobookshelf"
name = "Audiobookshelf"
description.en = "Audiobook server for managing and playing your audiobooks"
description.fr = "Serveur de livres audio pour gérer et lire vos livres audio"

version = "2.3.1~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "AGPL-3.0-only"
website = "https://audiobookshelf.org/"
demo = "https://audiobookshelf.org/"
userdoc = "https://www.audiobookshelf.org/docs"
code = "https://github.com/advplyr/audiobookshelf"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false 
sso = false
disk = "50M" 
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/advplyr/audiobookshelf/archive/refs/tags/v2.3.1.tar.gz"
        sha256 = "9b83adf2eaa0c5e97c060924efa971f74ea26d3b1db72f47f9413d8630acd0aa"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "ffmpeg"
